This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./PFG-Unai-Alonso.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file PFG-Unai-Alonso.acn....done (77 entries accepted, 0 rejected).
Sorting entries....done (606 comparisons).
Generating output file PFG-Unai-Alonso.acr....done (64 lines written, 0 warnings).
Output written in PFG-Unai-Alonso.acr.
Transcript written in PFG-Unai-Alonso.alg.
